blank_issues_enabled: false
contact_links:
  - name: Support Request
    url: https://discord.gg/8KgkRBA
    about: You can obtain support here.
  - name: Latest Builds
    url: https://jenkins.addstar.com.au
    about: Please ensure your using the latest release if reporting bugs
